Complexity_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('regions.urls')),
]

regions/urls.py
from django.urls import path
from .views import HomePage, RegionCreateView, LinearProgrammingModel, ReinicioPage, RegionListView

# Create your urls here.

app_name = 'regions'

urlpatterns = [
    path('', HomePage.as_view(), name='home_page'),
    path('region_list/', RegionListView.as_view(), name='list_region_page'),
    path('region_create/', RegionCreateView.as_view(), name='create_region_page'),
    path('lp_model/', LinearProgrammingModel.as_view(), name='lp_model_page'),
    path('reiniciar', ReinicioPage.as_view(), name='reinicio_page'),
]

regions/models.py
from django.db import models

# Create your models here.
class Region(models.Model):
    region_name = models.CharField(verbose_name= 'region name', max_length=20)
    existing_population = models.IntegerField(verbose_name='existing population')
    current_personal = models.IntegerField(verbose_name='current personal')
    required_personal = models.IntegerField(verbose_name='required personal')
    generated_costs = models.FloatField(verbose_name='generated costs')
    deads = models.IntegerField(verbose_name='deads')
    qualification = models.IntegerField(verbose_name='qualification')

    class Meta:
        verbose_name = "Región"
        verbose_name_plural = "Regiones"

    def __str__(self):
        return self.region_name

regions/forms.py
from django import forms
from .models import Region

# Create your forms here.

class FormData(forms.Form):

    fans = forms.IntegerField(max_value=10000, min_value=1, label=False)
    personal = forms.IntegerField(max_value=10000, min_value=1, label=False)
    budget = forms.FloatField(max_value=10000000000, min_value=1000000, label=False)
    qualification = forms.IntegerField(max_value=10000, min_value=0, label=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2'})
            self.fields[field].widget.attrs.update({'placeholder': f'Type the total {field}'})

class RegionForm(forms.ModelForm):

    class Meta:
        model = Region
        fields = ('__all__')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({'class': 'form-control mb-2'})
            self.fields[field].widget.attrs.update({'placeholder': f'Type the {self.fields[field].label}'})
            self.fields[field].label = False
            

regions/views.py
from django.views.generic import ListView, CreateView, RedirectView
from django.http import HttpResponse,JsonResponse
from django.core.serializers import serialize
from django.shortcuts import redirect
from django.urls import reverse_lazy
from .models import Region
from .forms import FormData, RegionForm
from .classes.generar_tabla import LinearProgramming


# Create your views here.

class HomePage(ListView):
    model = Region
    template_name = 'regions/home.html'
    context_object_name = 'regiones'
    extra_context = {'form': FormData, 'regionform': RegionForm}


class RegionListView(ListView):
    model = Region
    
    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        data = serialize('json', self.object_list)
        return HttpResponse(data, 'application/json')


class RegionCreateView(CreateView):
    model = Region
    form_class = RegionForm
    success_url = reverse_lazy('regions:home_page')

    # No se podrá acceder a esta vista si se conoce la url, porque en ese caso se redirecciona a home_page
    def get(self, request, *args, **kwargs):
        return redirect('regions:home_page')

    def form_valid(self, form):
        self.object = form.save()
        mensaje = f'{self.model.__name__} registrada correctamente!'
        return JsonResponse({'message': mensaje})

    def form_invalid(self, form):
        mensaje = f'La {self.model.__name__} no se ha podido registrar!'
        return JsonResponse({'message': mensaje, 'error': form.errors})

class LinearProgrammingModel(ListView):
    model = Region
    template_name = 'regions/home.html'
    context_object_name = 'regiones'
    extra_context = {'form': FormData, 'regionform': RegionForm}

    def get(self, request, *args, **kwargs):
        informacion = [[region.existing_population, region.current_personal, region.required_personal, region.generated_costs, region.deads, region.qualification] for region in self.get_queryset()]
        objeto = LinearProgramming(numero_regiones=len(informacion))
        tabla = objeto.construirTabla(informacion)
        tabla_modelo = objeto.generarTabla(tabla)
        valores_regiones, maximo_valor = objeto.modelo(tabla_modelo, request.GET)
        distribucionVentiladores, distribucionProfesionales, distribucionPresupuesto, distribucionCualificacion = objeto.distribucionElementos(valores_regiones, tabla_modelo)
        self.extra_context.update({
            'distribucionVentiladores':distribucionVentiladores,
            'distribucionProfesionales':distribucionProfesionales,
            'distribucionPresupuesto':distribucionPresupuesto,
            'distribucionCualificacion':distribucionCualificacion
            })
        return super().get(self, request, *args, **kwargs)

class ReinicioPage(RedirectView):
    url = reverse_lazy('regions:home_page')
    
    def post(self, request, *args, **kwargs):
        Region.objects.all().delete()
        return super().post(self, request, *args, **kwargs)

regions/templates/regions/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    
    {% block extra_css %} {% endblock extra_css %}
      
    <title> {% block title %} {% endblock title %} </title>

  </head>
  <body>

    <div class="row">
      <img class="col-10" src="{% static 'regions/img/coronavirus.jpeg' %}" style="width: 100%; height: 120px;">
      <div class="col-2" style="background-color: #989391"></div>
  </div>

    {% block contents %} {% endblock contents %}
    
    {% block extra_js %} {% endblock extra_js %}
    
  </body>
</html>

regions/templates/regions/generator.html
{% extends 'regions/base.html' %}

{% block title %} Generator {% endblock title %}

{% block contents %}


{% if 'num_regions' %}
    {{ num_regions }}
{% endif %}
    

{% endblock contents %}

regions/templates/regions/home.html
{% extends 'regions/base.html' %}
{% load static %}
{% block title %} Corona Complejidad {% endblock title %}

{% block contents %}


<div class="row">
    <div class="mx-auto col-sm" style="width: 200px; padding: 65px;">
        <div id="success_message"></div>
        <form action="{% url 'regions:create_region_page' %}" method="post" id="region_form">
            {% csrf_token %}
            <div class="form-group">
                {{ regionform.as_p }}
            </div>
        </form>
        <button onclick='SaveData("{{ csrf_token }}")' class="btn btn-primary" style="margin-top: 20px; width: 100%">Ingresar</button>
    </div>

    <div class="mx-auto col-sm" style="width: 200px; padding: 65px;">
        <form action="{% url 'regions:lp_model_page' %}" method="get" id="data_form">
            {% csrf_token %}
            <div class="form-group">
                {{ form.as_p}}
            </div>
        </form>
        <button type="submit" class="btn btn-primary" style="margin-top: 20px; width: 100%;">Generar modelo</button>
    </div>

</div>

<div class="row">

    <div class="col-7" style="margin-left: 1%;">
        <div>
            <table class="table table-striped" id="data_table">
                <thead>
                    <tr>
                        <th scope="col">Región</th>
                        <th scope="col">Población</th>
                        <th scope="col">Estaciones actuales</th>
                        <th scope="col">Personal requerido</th>
                        <th scope="col">Costos</th>
                        <th scope="col">Muertes</th>
                        <th scope="col">Cualificación</th>
                    </tr>
                </thead>

                <tbody>
                    {% for region in regiones %}
                        <tr>
                            <td>{{ region.region_name }}</td>
                            <td>{{ region.existing_population }}</td>
                            <td>{{ region.current_personal }}</td>
                            <td>{{ region.required_personal }}</td>
                            <td>{{ region.generated_costs }}</td>
                            <td>{{ region.deads }}</td>
                            <td>{{ region.qualification }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>


    <div class="col-4">
        
        <h1 style="margin-bottom: 25px">RESULTADOS</h2>
        {% if 'distribucionVentiladores' %}
        <div class="form-group">

            {% for valor in distribucionVentiladores %}
            {% if  valor != 0 %}
            <p> A la región {{forloop.counter}} le corresponden {{ valor }} ventiladores </p>
            {% endif %}
            {% endfor %}

            {% for valor in distribucionProfesionales %}
            {% if  valor != 0 %}
            <p> A la región {{forloop.counter}} le corresponden {{ valor }} profesionales de la salud </p>
            {% endif %}
            {% endfor %}

            {% for valor in distribucionPresupuesto %}
            {% if  valor != 0 %}
            <p> A la región {{forloop.counter}} le corresponden {{ valor }} millones de pesos </p>
            {% endif %}
            {% endfor %}

            {% for valor in distribucionCualificacion %}
            {% if  valor != 0 %}
            <p> A la región {{forloop.counter}} le corresponde {{ valor }} de cualificación </p>
            {% endif %}
            {% endfor %}
            
            {% endif %}
        </div>
    </div>     
</div>


<div class="row mx-auto">
    <form style="width: 100%" action="{% url 'regions:reinicio_page' %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary" style="width: 60%; margin-left: 20%; margin-top: 40px; margin-bottom: 30px;">Nuevo modelo</button>
    </form>  
</div>

{% endblock contents %}


{% block extra_js %}
    <script src="{% static 'regions/js/peticiones.js' %}"></script>
{% endblock extra_js %}
    